### ISSUE TITLE
[Feature]: docstrings for NamedTrajectory struct and consttructors

### ISSUE THREAD

**Issue by aarontrowbridge** [aarontrowbridge/NamedTrajectories.jl#39]
### Feature Description

We need docstrings attached to the struct and methods in [`src/struct_named_trajectory`](https://github.com/aarontrowbridge/NamedTrajectories.jl/blob/main/src/struct_named_trajectory.jl)

#### Implementation requirements
- add docstrings to all of the functions in `src/struct_named_trajectory` using the [Blue style](https://github.com/JuliaDiff/BlueStyle?tab=readme-ov-file#documentation) guidelines
- populate the docs file [`docs/literate/man/constructors.jl`](https://github.com/aarontrowbridge/NamedTrajectories.jl/blob/main/docs/literate/man/constructors.jl) with examples using [Literate.jl](https://github.com/fredrikekre/Literate.jl), see the docs script [`docs/literate/quickstart.jl`](https://github.com/aarontrowbridge/NamedTrajectories.jl/blob/main/docs/literate/quickstart.jl) for reference

### Importance

1 (lowest)

### What does this feature affect?

- [ ] construction
- [ ] methods
- [ ] plotting
- [ ] documentation
- [ ] tests
- [ ] other (please specify below)

**Comment by ErikQQY** [comment]
Could you also assign me this issue?😄 @aarontrowbridge
